# Generated by Django 3.2.5 on 2022-03-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_0',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('xm', models.CharField(max_length=16)),
                ('xb', models.CharField(max_length=5)),
                ('mz', models.CharField(max_length=5)),
                ('nl', models.IntegerField()),
                ('dh', models.CharField(max_length=13)),
                ('xx', models.CharField(max_length=32)),
                ('xl', models.CharField(max_length=32)),
                ('zy', models.CharField(max_length=32)),
                ('zwjs', models.CharField(max_length=200)),
                ('gzjl', models.CharField(max_length=200)),
                ('jyjl', models.CharField(max_length=200)),
                ('hjjl', models.CharField(max_length=200)),
                ('ahtc', models.CharField(max_length=200)),
                ('qwxz', models.CharField(max_length=200)),
                ('fjxx', models.CharField(max_length=200)),
                ('zcsj', models.DateTimeField(blank=True, null=True)),
                ('zhzt', models.IntegerField()),
            ],
        ),
    ]
