# Generated by Django 3.2.5 on 2022-03-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QZXT', '0002_auto_20220308_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_0',
            name='jg',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='user_0',
            name='nl',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
