# Generated by Django 3.2.5 on 2022-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QZXT', '0003_auto_20220308_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('jgdm', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('qymc', models.CharField(max_length=64)),
                ('fzzh', models.CharField(max_length=16)),
                ('qydz', models.CharField(max_length=64)),
                ('qyxz', models.CharField(max_length=64)),
                ('zyyw', models.CharField(max_length=64)),
                ('djsj', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_1',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('yhjb', models.IntegerField()),
                ('jgdm', models.CharField(max_length=16)),
                ('qymc', models.CharField(max_length=64)),
                ('xm', models.CharField(max_length=16)),
                ('xb', models.CharField(max_length=16)),
                ('dh', models.CharField(max_length=16)),
                ('zw', models.CharField(max_length=16)),
                ('zcsj', models.DateTimeField(blank=True, null=True)),
                ('zhzt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_2',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
    ]
