# Generated by Django 3.2.5 on 2022-03-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QZXT', '0005_remove_user_1_qymc'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('mc', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('sj', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
