# Generated by Django 3.2.5 on 2022-03-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QZXT', '0006_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zwlb', models.CharField(max_length=16)),
                ('zwmc', models.CharField(max_length=50)),
                ('xz', models.CharField(max_length=16)),
                ('gzdz', models.CharField(max_length=50)),
                ('nr', models.CharField(max_length=50)),
                ('qtxx', models.CharField(max_length=50)),
                ('fbsj', models.CharField(max_length=50)),
                ('fbz', models.CharField(max_length=50)),
                ('lxdh', models.CharField(max_length=50)),
                ('jgdm', models.CharField(max_length=50)),
            ],
        ),
    ]
