# Generated by Django 3.2.5 on 2022-03-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QZXT', '0007_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='fbzyhm',
            field=models.CharField(default='-1', max_length=50),
        ),
    ]
