# Generated by Django 3.2.5 on 2022-03-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QZXT', '0010_auto_20220322_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tdsj', models.CharField(max_length=50)),
                ('zt', models.CharField(max_length=20)),
                ('hf', models.CharField(max_length=50)),
                ('zwid', models.IntegerField()),
                ('fbz', models.CharField(max_length=16)),
                ('tdz', models.CharField(max_length=16)),
            ],
        ),
    ]
