# Generated by Django 3.2.5 on 2022-03-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QZXT', '0011_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='hf',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
