# Generated by Django 3.2.5 on 2022-03-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QZXT', '0012_alter_resume_hf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user0', models.CharField(max_length=32)),
                ('user1', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user0', models.CharField(max_length=32)),
                ('user1', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('content', models.CharField(max_length=100)),
                ('sender', models.IntegerField()),
            ],
        ),
    ]
